### ISSUE TITLE
Publish button ignoring ACLs + no correct info message shown

### ISSUE THREAD

**Issue by koenkicken** [orbinson/aem-dictionary-translator#23]
When selected a dictionary or label, the publish button is always available and do not take ACLs into account

You get always a successful message (`Label/Dictionary published`), despite it not being published if you do not have the correct permissions. 
( in the Logs it is visible it was not published: 
`*ERROR* [[0:0:0:0:0:0:0:1] [1709119475475] POST /apps/aem-dictionary-translator/content/granite/dialog/dictionary/publish/items/properties/items/columns/items/column/items/form HTTP/1.1] be.orbinson.aem.dictionarytranslator.servlets.action.ReplicateDictionaryServlet ReplicationException occurred when trying to replicate dictionary in ReplicateDictionaryServlet`
)

Also when you dont have the rights to create a label or update a label, you always get the info message `Label saved` while the operation was not successful

**Comment by bdhoine** [comment]
Issue was solved by linked pull request, error is shown in the interface now
