### ISSUE TITLE
Generic error message instead of `Label already exists`

### ISSUE THREAD

**Issue by koenkicken** [orbinson/aem-dictionary-translator#24]
No clear indication when trying to create a label which name already exists.

Test steps:
1. Create a label with name `test`
2. Submit dialog to create the label
3. Create a new label again with the same name `test`

Expected behaviour:
A clear message should be shown to indicate this label already exists

Actual behaviour:
A generic error message `Server Error` is being shown

<img width="599" alt="image" src="https://github.com/orbinson/aem-dictionary-translator/assets/61004582/08d21597-3158-4158-8aae-f7666eb3733c">

**Comment by royteeuwen** [comment]
Fixed in PR #30
