### ISSUE TITLE
Not able to see/create any dictionary

### ISSUE THREAD

**Issue by rdb987** [orbinson/aem-dictionary-translator#25]
I have installed the tool on my AEM on premise (6.5 with SP 6.5.21). 
Unfortunately the tool for me doesn't work at all. I am not able to create any dictionary or seeing the existing one.
Check screenshots 
![image](https://github.com/orbinson/aem-dictionary-translator/assets/16901319/5f5ac60c-acab-4884-983f-b21c7293374c)

![image](https://github.com/orbinson/aem-dictionary-translator/assets/16901319/78e52d16-4252-4011-b440-f12bd28ada90)

We would like to use this tool for our AEM implementations but not possible if is like that...

**Comment by rdb987** [comment]
Seems like a dependency issue:
![image](https://github.com/orbinson/aem-dictionary-translator/assets/16901319/1716ab97-7b14-4dec-9b55-d7a4fd5ab6d0)

**Comment by rdb987** [comment]
I have the impression the dependency for all packages is using the AEM cloud version (dependencies from sdk, instead of uber-jar...).

**Comment by bdhoine** [comment]
in the latests version the dependency on sling distribution which is cloud only is not present anymore, please use the latest version before reporting issues :) if you do notice it is not working on prem, this tool is indeed only compiled with the cloud sdk api's

**Comment by bdhoine** [comment]
feel free to create a pull request ;)

**Comment by bdhoine** [comment]
FYI: It did work on AEM 6.5 so that's why it's in the README. You can try to check out the code and compile against the latests uberjar. Our focus at this moment is on AEMaaCS because on prem you can use the OOTB translator.

**Comment by bdhoine** [comment]
I did a small test with SP21 and it's indeed broken and it's not an easy fix. At the moment we don't have the need to use this on prem so we will not look further into this.

I updated the README file that only AEMaaCS is supported

**Comment by rdb987** [comment]
Thanks for the clarifications anyway.
