### ISSUE TITLE
Issue with adding new language to the existing dictionary (when camel case keys are used)

### ISSUE THREAD

**Issue by mpankratiev** [orbinson/aem-dictionary-translator#28]
1) Create a label
<img width="624" alt="image" src="https://github.com/user-attachments/assets/449d5c9f-338c-471b-a83e-88ee489147e5">

2) Check how properties are stored. Note that sling:key is added in uppercase and node name goes in lowercase
<img width="1064" alt="image" src="https://github.com/user-attachments/assets/41ce9650-d381-45fa-b86e-4377842c1492">

3) Add a new language
<img width="1717" alt="image" src="https://github.com/user-attachments/assets/c861e3f8-d063-4bb6-acae-061e9ca44333">

4) Add translation for the newly created language
<img width="1723" alt="image" src="https://github.com/user-attachments/assets/a13861ad-69eb-49b4-b495-0850b2f6d41a">

5) Check how properties are stored for the newly created language. sling:key property is not added and node name goes in lowercase which leads to the issue with resolving for the translation (node name is used as a key when sling:key is missing).
<img width="1234" alt="image" src="https://github.com/user-attachments/assets/c50818a7-0149-4659-9885-124afb620989">

**Comment by royteeuwen** [comment]
Fixed in release https://github.com/orbinson/aem-dictionary-translator/releases/tag/1.1.3
