### ISSUE TITLE
Labels creation blocked due to case-insensitive 

### ISSUE THREAD

**Issue by jmagdrod** [orbinson/aem-dictionary-translator#31]
Dictionary translator tool treats labels with different capitalization as identical, blocking the creation of a new label.
The system should allow labels with names differing by capitalization (e.g., "Email" and "email") to coexist as separate entries.

Please find attached a video with the use case:
https://github.com/user-attachments/assets/3b84e6c4-cd63-4fe3-a9cd-815aea082730

**Comment by kwin** [comment]
The issue is `JcrUtil.createValidName(String)` being used in https://github.com/orbinson/aem-dictionary-translator/blob/3e77134e883e4107368c31d54b2f227d09ab36d4/core/src/main/java/be/orbinson/aem/dictionarytranslator/servlets/action/CreateLabelServlet.java#L85. This one only emits lower case characters.

**Comment by jmagdrod** [comment]
This may require some adjustments because it has impact into other features. 
For example the delete label action, where the [dialog](https://github.com/orbinson/aem-dictionary-translator/blob/main/ui.apps/src/main/content/jcr_root/apps/aem-dictionary-translator/content/granite/dialog/dictionary/label/delete/.content.xml) will call the following servlet, splitting the labels by comma in this line:
https://github.com/orbinson/aem-dictionary-translator/blob/3e77134e883e4107368c31d54b2f227d09ab36d4/core/src/main/java/be/orbinson/aem/dictionarytranslator/servlets/action/DeleteLabelServlet.java#L46

If any entry contains "," char it will break the deleteLabel feature. 
Previous method `JcrUtil.createValidName(String)` escapes (replaced with "_") that char but ` Text.escapeIllegalJcrChars(String) ` do not, so when the the servlet tries to split the labels, it ends in a wrong label path:
https://github.com/orbinson/aem-dictionary-translator/blob/3e77134e883e4107368c31d54b2f227d09ab36d4/core/src/main/java/be/orbinson/aem/dictionarytranslator/servlets/action/DeleteLabelServlet.java#L56

As possible solution the same [chars_mapping](url) used by `JcrUtil.createValidName(String)` could be replaced by "_" after ` Text.escapeIllegalJcrChars(String)` is done, in this way case-insensitive will continue working and other functionalities won't be impacted.

**Comment by kwin** [comment]
I think instead of splitting, the delete servlet should use multiple label parameters, that way there is no need for a reserved character. Will rework the [PR](https://github.com/orbinson/aem-dictionary-translator/pull/34) accordingly

**Comment by jmagdrod** [comment]
In that case, please review replicateLanguageServlet as well:
https://github.com/orbinson/aem-dictionary-translator/blob/3e77134e883e4107368c31d54b2f227d09ab36d4/core/src/main/java/be/orbinson/aem/dictionarytranslator/servlets/action/ReplicateLabelServlet.java#L45
