### ISSUE TITLE
Labels including whitespaces are replaced with "_" which in frontend side

### ISSUE THREAD

**Issue by jmagdrod** [orbinson/aem-dictionary-translator#32]
* Note that this isssue is reproducible when the dictionary contains more than 1 label.

When a new label with whitespaces is created, the node name will be generated using the sling:key replacing the whitespaces with underscores.
Example:
![image](https://github.com/user-attachments/assets/0a2e4045-d1a8-4df3-be2f-cf1ee40de3cf)

The tool will show in the label list the node name of these labels instead of the sling:key. The problem comes when a new translation is added to the label. The form submission will create the node without sling:key property and in this case, the label exposed into the final json will be the node name, instead of the sling:key
![image](https://github.com/user-attachments/assets/3d320208-cac3-43e0-ab38-9c3749cb0f58)
![image](https://github.com/user-attachments/assets/db2ea5ea-9366-42af-b840-3d5ef5032dd9)

**Comment by jmagdrod** [comment]
Steps to reproduce the issue(adding some example of names and language code):
1. Create new dictionary "test" with one language "sq_al".
2. Enter in the dictionary and create a new label with whitespaces "this is a test" and add  a translation value "test" to "sq_al" language:
![image](https://github.com/user-attachments/assets/cfb9da5a-350d-42fb-a55a-bb1bab29cd73)

3. Go back to main dictionaries panel, select "test" dictonary and add a new language "en".
![image](https://github.com/user-attachments/assets/0acba898-c714-4c80-8c26-6048dc9c0e7c)

4. Enter again in the "test" dictionary. The label is now changed to "this_is_a_test". 
![image](https://github.com/user-attachments/assets/6f15257a-1e2f-4304-b676-84e98bf42271)

5. Add a translation value to the "en" and check the resource. It does not contain the property sling:key.
![image](https://github.com/user-attachments/assets/b373a026-a269-42c2-9dee-79f2b4a2c156)

6. Check the i18n translation json file exposed for "en", it's using node name instead of sling:key because is missing in the resource: http://localhost:4502/libs/cq/i18n/dict.en.json
![image](https://github.com/user-attachments/assets/86d49435-670a-4fce-b1ff-5db12d052aa1)

**Comment by kwin** [comment]
The problem is that after step 3, the `sling:key` from the first language is no longer evaluated.
