### ISSUE TITLE
LabelResourceProvider only detects languages having resource name = jcr:language value

### ISSUE THREAD

**Issue by kwin** [orbinson/aem-dictionary-translator#37]
Multiple methods within `LabelResourceProvider` rely on the fact that the languages returned from `DictionaryService.getLanguages(Resource)` are equal to the child resource name. This is not necessarily the case as can be seen  in the example https://sling.apache.org/documentation/bundles/internationalization-support-i18n.html#sample-resources where the resource containing `en` is named `English`.

This incorrect dereferencing happens e.g. in 

1. https://github.com/orbinson/aem-dictionary-translator/blob/3e77134e883e4107368c31d54b2f227d09ab36d4/core/src/main/java/be/orbinson/aem/dictionarytranslator/services/LabelResourceProvider.java#L64 
2. https://github.com/orbinson/aem-dictionary-translator/blob/3e77134e883e4107368c31d54b2f227d09ab36d4/core/src/main/java/be/orbinson/aem/dictionarytranslator/services/LabelResourceProvider.java#L50
3. https://github.com/orbinson/aem-dictionary-translator/blob/3e77134e883e4107368c31d54b2f227d09ab36d4/core/src/main/java/be/orbinson/aem/dictionarytranslator/services/LabelResourceProvider.java#L104 and
4. https://github.com/orbinson/aem-dictionary-translator/blob/3e77134e883e4107368c31d54b2f227d09ab36d4/core/src/main/java/be/orbinson/aem/dictionarytranslator/services/LabelResourceProvider.java#L120

**Comment by royteeuwen** [comment]
Fixed in https://github.com/orbinson/aem-dictionary-translator/releases/tag/1.1.4
