### ISSUE TITLE
LabelResourceProvider incorrectly assumes that all languages share the same node name for the same key

### ISSUE THREAD

**Issue by kwin** [orbinson/aem-dictionary-translator#39]
The names of the `sling:MessageEntry` nodes within different languages can be chosen arbitrarily (in case the `sling:key` property is set). Even the same entry might have different node names in different languages. This is currently not correctly considered in 

1. https://github.com/orbinson/aem-dictionary-translator/blob/3e77134e883e4107368c31d54b2f227d09ab36d4/core/src/main/java/be/orbinson/aem/dictionarytranslator/services/LabelResourceProvider.java#L50 and 
2. https://github.com/orbinson/aem-dictionary-translator/blob/3e77134e883e4107368c31d54b2f227d09ab36d4/core/src/main/java/be/orbinson/aem/dictionarytranslator/services/LabelResourceProvider.java#L66

**Comment by royteeuwen** [comment]
Darnit, sad that the specs make it so unnecessarily complex hehe. We have built all our i18n dictionaries by using this UI, so these situations never occur in that case. I'll see if this one is easily fixable.

**Comment by kwin** [comment]
This probably requires some major refactoring (and also some caching, as the lookup is much more effort). I think just documenting this limitation in the README is acceptable is this is probably an edge case (and I don't consider this best practice either).
