### ISSUE TITLE
Users with only read rights can see editing tools

### ISSUE THREAD

**Issue by michielspiritus** [orbinson/aem-dictionary-translator#42]
Steps to Reproduce:

-  Assign a user to the sitename-web-base group, which has read-only permissions.
- As the read-only user:
- Possibility to edit dictionaries. It looks like it saved the edit, but it does not happen.
- Possibility to create a language copy at sitename content and experience fragment. It looks like it create a language copy, but it does not happen.
- Possibility to add to the configuration. When you try to save it, you will receive a notification 'no write access'.

**Comment by bdhoine** [comment]
@michielspiritus the description is a bit vague, can make make it more clear? :)
