### ISSUE TITLE
Time out exception when publishing large dictionaries

### ISSUE THREAD

**Issue by jmagdrod** [orbinson/aem-dictionary-translator#44]
When a dictionary contains a large number of keys and message entries the publication returns a timeout error because the servlet processing time is taking more than 60 seconds.

A possible solution could be processing this as workflow.

![image](https://github.com/user-attachments/assets/61a0b033-5c2a-4f66-a7da-54b580a52686)

**Comment by royteeuwen** [comment]
@jmagdrod a workflow would indeed be a perfect solution for this. I wont have the time to fix it this week so if it's urgent I'm always open for contributions!

**Comment by royteeuwen** [comment]
@jmagdrod  do you have test content ready to test my PR :)?
