### ISSUE TITLE
Clarify relation to CQ-4357471

### ISSUE THREAD

**Issue by kwin** [orbinson/aem-dictionary-translator#47]
The new AEMaaCS release notes for 18459 list the following fix: 

> CQ-4357471: Add support for i18n Dictionaries Translation in AEMaaCS

(https://experienceleague.adobe.com/en/docs/experience-manager-cloud-service/content/release-notes/maintenance/latest?lang=en)

Does this mean that this tool becomes obsolete?

**Comment by jmagdrod** [comment]
The new feature introduced on the release 18459 only covers the dictionary translation through exports and imports of [XLIFF ](https://en.wikipedia.org/wiki/XLIFF) file format. 
But this new tool does not expose any dictionary interface allowing the i18n translation management. I don't see it as a replacement to aem-dictionary-translator tool.

Some extra info:
- The tool is accesible from: `http://<hostname>:<port-number>/libs/cq/i18n/gui/translator.html`
- Servlet `com.adobe.granite.i18n.impl.DictImportExportServlet` that renders the dictionaries as XLIFF format contained in [com.adobe.granite.i18n](https://mvnrepository.com/artifact/com.adobe.granite/com.adobe.granite.i18n/5.5.10) bundle: `http://<hostname>:<port-number>/libs/granite/i18n/de.dict.xliff` 
- The new dictionaries will be stored under `/content/cq:i18n`

**Comment by kwin** [comment]
The tool is also not yet linked from the tools section. Here is a screenshot of it:

![Screenshot 2024-11-07 at 13 04 46](https://github.com/user-attachments/assets/9e13e9c3-294e-4f46-adb9-4548578b65ba)

There seem to be some kind of overlay mechanism introduced, so that dictionaries in `/content/cq:i18n` seem to take precedence over ones from `/apps` or `/libs`

**Comment by royteeuwen** [comment]
Hmm, so does that mean there is a non-open source extension of the sling i18n resourcebundleprovider? Don't remember seeing any PR's about this :D

**Comment by kwin** [comment]
I dug a littlebit deeper, but haven't found any implementation which changes anything about the search order outlined in https://sling.apache.org/documentation/bundles/internationalization-support-i18n.html#resourcebundle-hierarchies. So in fact this feature doesn't seem to allow to overwrite an existing translation for the same locale from /apps in /content/cq:i18n, it only works for translations not yet existing for the key and locale in /apps or /libs.

**Comment by royteeuwen** [comment]
OK good to know. I'll wait until the docs of AEM are updated before maybe updating the readme here to point to the difference

**Comment by kwin** [comment]
Next to documentation would also be good to add a button to easily provide a way to export in XLIFF format (next to CSV).
