### ISSUE TITLE
Shortcut to open Chrome Developer tools not working on AEM Dictionary Translator pages

### ISSUE THREAD

**Issue by kwin** [orbinson/aem-dictionary-translator#53]
There seem to be a conflict of shortcuts with Chrome Mac OS on http://localhost:4502/tools/translation/dictionaries.html.

The default shortcut to open Developer Tools is `Option + Command + i`. However this opens the `Delete Language` overlay within the AEM Dictionary Translator.

**Comment by bdhoine** [comment]
We might need to reconsider the assignment of this shortcut or see if we can report this if the Granite UI does not detect the difference between chained shortcuts

**Comment by kwin** [comment]
I think the problem is the conflict with the import command (https://github.com/orbinson/aem-dictionary-translator/blob/d89d9033282a89c7360b7738131a905be9f3154e/ui.apps/src/main/content/jcr_root/apps/aem-dictionary-translator/content/dictionaries/.content.xml#L98) which is bound to `i`.

According to https://developer.adobe.com/experience-manager/reference-materials/6-5/granite-ui/api/jcr_root/libs/granite/ui/components/coral/foundation/collection/action/index.html

> Command used as a shortcut for the action. It accepts single keys, sequenques and key modifiers. Command will override actionConfigName.

> When ctrl or cmd is used, it will be normalized based on the client’s OS.

Although no modifier is given here it seems that something fishy is going on. Pressing `d` has the same effect as `Option + i` and `Command + Option + i`. All open the "delete language" overlay.
