### ISSUE TITLE
Pressing shortcut multiple times opens multiple modal overlays

### ISSUE THREAD

**Issue by kwin** [orbinson/aem-dictionary-translator#54]
When leveraging e.g. the shortcut `d` to `Delete Language` within `/tools/translation/dictionaries.html` a modal overlay window is exposed (which disables the action bar). However pressing `d` again opens another overlay on top of it.

**Comment by bdhoine** [comment]
I suspect this is an issue with the Granite UI implementation. If needed we need to create an Adobe support ticket for this. We will look into this and provide an update when we investigated it

**Comment by bdhoine** [comment]
closing this one as the shortcut was removed in `1.2.0`
