### ISSUE TITLE
Language drop-down should expose both language and optionally country name

### ISSUE THREAD

**Issue by kwin** [orbinson/aem-dictionary-translator#55]
The data source for available languages just leverages the `TranslationConfig.getLanguages()` to retrieve the available languages. That returns a Map with key being the combination of country code (optional) with language code (mandatory) (separated by "_") and as value just a label for the language (disregarding the country).

The drop-down being used in Page Properties -> Advanced -> Language (`/libs/wcm/foundation/components/basicpage/v1/basicpage/tabs/advanced/items/column/items/section1/items/language/datasource`) leveraging the data source `cq/gui/components/common/datasources/languages` (with its source being `/libs/cq/gui/components/common/datasources/languages/languages.jsp`) however exposes the following format:

`<Language Label> (<Country Label>)` (without exposing any ISO codes). 

I think that is better suited for choosing the proper language country combination. Particularly when it comes to 'artificial countries' (i.e. markets which span more than one country, like middle africa). Those usually leverage one of the reserved country codes from <https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2#User-assigned_code_elements>. Maybe one can even rather filter on top of the data source `cq/gui/components/common/datasources/languages` in https://github.com/orbinson/aem-dictionary-translator/blob/main/core/src/main/java/be/orbinson/aem/dictionarytranslator/servlets/datasource/AvailableLanguageDatasource.java. That way both drop-downs look the same.

**Comment by bdhoine** [comment]
Thanks for reporting and the pointers. I agree we should change it that the dropdown is aligned with the one from the page properties.

**Comment by kwin** [comment]
I am gonna prepare a PR for that.

**Comment by kwin** [comment]
@bdhoine @royteeuwen Is it possible to release a new version including this change?

**Comment by bdhoine** [comment]
@kwin github and maven release done ;) might take some time to propagate the version to central: https://github.com/orbinson/aem-dictionary-translator/releases/tag/1.2.0
